repos:
  - repo: local
    hooks:
      - id: vale
        name: vale
        description: Run vale on your text
        entry: bash -c 'git diff --cached --name-status | cut -f2 | xargs vale'
        language: golang
        types: [text]